сreate top-line
volkov73/porten-web pull request #2
Opened 2022-08-14 10:51 UTC by volkov73

2022-08-14 11:02 UTC, inferal73 requested changes
- все картинки нужно переименовать осознанно, ну типа не Vector 2.svg а что то типа arrow_right.svg
- используй для позиционирования  flex

2022-08-14 11:04 UTC, volkov73 commented on src/Pictures/Vector 2.svg:Zone.Identifier
> +[ZoneTransfer]
Создался автоматически вместе с .svg фалом

2022-08-14 11:04 UTC, volkov73 commented on src/Pictures/Vector.svg:Zone.Identifier
> +[ZoneTransfer]
Создался автоматически вместе с .svg фалом

2022-08-14 11:04 UTC, volkov73 commented on src/Pictures/phone.svg:Zone.Identifier
> +[ZoneTransfer]
Создался автоматически вместе с .svg фалом

2022-08-14 16:11 UTC, inferal73 commented on src/Pictures/Vector.svg:Zone.Identifier
> +[ZoneTransfer]
удали его, ну и когда git add . делаешь - смотри что попадает в стек

2022-08-14 16:11 UTC, inferal73 commented on src/Pictures/phone.svg:Zone.Identifier
> +[ZoneTransfer]
см выше

2022-08-15 08:36 UTC, inferal73 requested changes

2022-08-15 08:36 UTC, inferal73 commented on .gitignore
> +arrow_right.svgZone.Identifier
не нужно этого в игноре, тем более в таком виде. Просто удаляй из папки перед добавленим в гит

2022-08-15 08:36 UTC, inferal73 commented on src/styles/styles.css
> +    position: relative;
не нужен ему relative, управлять через left и top тут плохая идея. используй фелкс

2022-08-15 08:36 UTC, inferal73 commented on src/styles/styles.css
> +    float: left;
флоаты тут тоже не нужны

2022-08-15 08:36 UTC, inferal73 commented on src/index.html
> +      <div class="top-line">
top-line должен быть один

2022-08-15 08:36 UTC, inferal73 commented on src/index.html
> +      <div class="top-line">
а в нем еще два блока left-side и right-side

2022-08-17 05:17 UTC, inferal73 requested changes

2022-08-17 05:17 UTC, inferal73 commented on src/styles/styles.css
> +    height: 44px;
height не нужен, добавь паддинг лучше верхний и нижний. они вместе с контентом создадут нужную высоту

2022-08-17 05:17 UTC, inferal73 commented on src/styles/styles.css
> +    margin: auto;
margin-left: auto
на все не нужно маржин

2022-08-17 05:17 UTC, inferal73 commented on src/styles/styles.css
> +    margin: auto;
тут вообще не нужен

2022-08-17 05:17 UTC, inferal73 commented on src/styles/styles.css
> +a:link {
не стилизуй через теги, только через классы

2022-08-17 05:17 UTC, inferal73 commented on src/styles/styles.css
> +a:link {
да и link псевдокласс не нужен

2022-08-18 08:27 UTC, inferal73 requested changes

2022-08-18 08:27 UTC, inferal73 commented on src/index.html
> +</html>
нет пустой строки в конце файла

2022-08-18 08:27 UTC, inferal73 commented on src/index.html
> +
лишний пробел

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +.phone-pict {
не pict, а icon

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +    margin: auto;
зачем?

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +    padding-right: 10px;
отступ внешний должен быть, он через margin задается

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +.log-in {
login без -

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +    margin: auto;
зачем?

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +.phone-numb {
зачем сокращать number?

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +.phone-numb:visited {
не нужно

2022-08-18 08:27 UTC, inferal73 commented on src/styles/styles.css
> +/*Вторая линия*/
мы не держим закомментированный код в гите

2022-08-19 09:17 UTC, inferal73 requested changes
нужно убрать из этой ветки все что не относится к top-bar

2022-08-19 17:56 UTC, inferal73 requested changes
- где твой контейнер который ширину выставляет?
- изображения забыл убрать лишние

2022-08-19 17:56 UTC, inferal73 commented on src/styles/styles.css
> +    font-family: 'PT Sans', sans-serif;
поставь на body

2022-08-19 17:56 UTC, inferal73 commented on .gitignore
> +.parcel-cache
пустая линия в конце нужна

2022-08-19 17:56 UTC, inferal73 commented on src/styles/styles.css
> +    margin: 1px 10px;
вот уверен что маржин в 1px вообще не нужен))

2022-08-19 17:56 UTC, inferal73 commented on src/styles/styles.css
> +    padding-left: 500px;
margin-left: auto

2022-08-19 17:56 UTC, inferal73 commented on src/styles/styles.css
> +    padding-left: 180px;
не нужно

2022-08-19 17:57 UTC, inferal73 requested changes
добавь css reset: https://meyerweb.com/eric/tools/css/reset/ отдельным css'ом перед своим

2022-08-22 07:37 UTC, inferal73 approved these changes

2022-08-22 08:24 UTC, merged